### ISSUE TITLE
Nano X

### ISSUE THREAD

**Issue by Altitude-Dashboard** [LedgerHQ/ledgerctl#16]
Running on MacOS Big Sur.
I have put Nano X in recovery mode:

ledgerctl info                  
Device: Ledger Nano X (0x33000004)
SE version: 1.2.4-5
MCU version: 2.10
Device is onboarded.
Device is running in RECOVERY mode.

I am trying to install a certificate:

ledgerctl install-ca "ledgerctl"
Traceback (most recent call last):
  File "/Users/codrut/Library/Python/3.8/bin/ledgerctl", line 8, in <module>
    sys.exit(cli())
  File "/Users/codrut/Library/Python/3.8/lib/python/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/codrut/Library/Python/3.8/lib/python/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/codrut/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/codrut/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/codrut/Library/Python/3.8/lib/python/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/codrut/Library/Python/3.8/lib/python/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/codrut/Library/Python/3.8/lib/python/site-packages/ledgerctl.py", line 224, in install_ca
    get_client().install_ca(name, pubkey_bytes)
  File "/Users/codrut/Library/Python/3.8/lib/python/site-packages/ledgerwallet/client.py", line 388, in install_ca
    self.apdu_secure_exchange(LedgerSecureIns.SETUP_CUSTOM_CERTIFICATE, data)
  File "/Users/codrut/Library/Python/3.8/lib/python/site-packages/ledgerwallet/client.py", line 210, in apdu_secure_exchange
    secret = self.authenticate(server)
  File "/Users/codrut/Library/Python/3.8/lib/python/site-packages/ledgerwallet/client.py", line 237, in authenticate
    self.apdu_exchange(LedgerIns.VALIDATE_CERTIFICATE, server_chain[i])
  File "/Users/codrut/Library/Python/3.8/lib/python/site-packages/ledgerwallet/client.py", line 199, in apdu_exchange
    raise CommException(
**ledgerwallet.client.CommException: Exception : Invalid status 69d5 (Cannot create custom secure channels on this device)**

**Comment by jibeee** [comment]
Installing custom certificates is not permitted on Nano X. Only apps delivered by Ledger can be installed on Nano X, unless you have a developer device.
