### ISSUE TITLE
LedgerHSMServer_pb2.py isn't compatible with protobuf >= 4.21.0

### ISSUE THREAD

**Issue by danroc** [LedgerHQ/ledgerctl#28]
When running `ledgerctl` within a new `venv` I got:

```
Traceback (most recent call last):
  File "venv/bin/ledgerctl", line 5, in <module>
    from ledgerctl import cli
  File "venv/lib/python3.10/site-packages/ledgerctl.py", line 9, in <module>
    from ledgerwallet.client import (
  File "venv/lib/python3.10/site-packages/ledgerwallet/client.py", line 27, in <module>
    from ledgerwallet.hsmserver import HsmServer
  File "venv/lib/python3.10/site-packages/ledgerwallet/hsmserver.py", line 5, in <module>
    from ledgerwallet.proto.LedgerHSMServer_pb2 import Request, Response
  File "venv/lib/python3.10/site-packages/ledgerwallet/proto/LedgerHSMServer_pb2.py", line 35, in <module>
    _descriptor.FieldDescriptor(
  File "venv/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

According to the [linked page](https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates):

> Version 4.21.0 is a new major version, following 3.20.1. The new version is based on the [upb library](https://github.com/protocolbuffers/upb) [...] Python upb requires generated code that has been generated from protoc 3.19.0 or newer.

Exporting `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python` does work as a workaround.

**Comment by tobim** [comment]
6a96cdbf4b32455a5f6727ded5164eed4b197aea introduced a `<4` version bound without explaining why. Can this be lifted?
