### ISSUE TITLE
OSError: open failed

### ISSUE THREAD

**Issue by briancorbin** [LedgerHQ/ledgerctl#59]
Hi, I'm having trouble connecting to my ledger nano s plus via the ledgerctl CLI

I have it connected and unlocked, and upon running any command that interfaces with the ledger, such as ```ledgerctl list``` I get the same response of

```
briancorbin@pop-os:~/Programming/ledgerctl$ ledgerctl list
Traceback (most recent call last):
  File "/home/briancorbin/.local/bin/ledgerctl", line 8, in <module>
    sys.exit(cli())
  File "/home/briancorbin/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/briancorbin/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/briancorbin/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/briancorbin/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/briancorbin/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/briancorbin/.local/lib/python3.10/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/briancorbin/Programming/ledgerctl/ledgerctl.py", line 135, in list_apps
    client = get_client()
  File "/home/briancorbin/Programming/ledgerctl/ledgerctl.py", line 99, in get_client
    return LedgerClient(private_key=get_private_key())
  File "/home/briancorbin/Programming/ledgerctl/ledgerwallet/client.py", line 180, in __init__
    self.device.open()
  File "/home/briancorbin/Programming/ledgerctl/ledgerwallet/transport/hid.py", line 30, in open
    self.device.open_path(self.path)
  File "hid.pyx", line 154, in hid.device.open_path
OSError: open failed

```

**Comment by briancorbin** [comment]
This seems to be an issue on Ubuntu (currently using popOS), as I got it working with my mac

**Comment by briancorbin** [comment]
I have installed the additional required packages listed in the readme for Ubuntu and Debian

**Comment by briancorbin** [comment]
Ah, solved this by adding https://github.com/LedgerHQ/udev-rules to my udev rules.d folder! :)
