### ISSUE TITLE
Missing 1 required positional argument: 'path'

### ISSUE THREAD

**Issue by andrepatta** [LedgerHQ/ledgerctl#7]
I'm trying to use this new lib to load apps into the Nano S/X but I'm having the following issue when doing `ledgerctl install app.json`:

`Traceback (most recent call last):
  File "/home/andrelpg/.local/bin/ledgerctl", line 11, in <module>
    sys.exit(cli())
  File "/home/andrelpg/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/andrelpg/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/andrelpg/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/andrelpg/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/andrelpg/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/andrelpg/.local/lib/python3.6/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/andrelpg/.local/lib/python3.6/site-packages/ledgerctl.py", line 145, in install_app
    client.install_app(app_manifest)
  File "/home/andrelpg/.local/lib/python3.6/site-packages/ledgerwallet/client.py", line 286, in install_app
    params = app_manifest.serialize_parameters()
  File "/home/andrelpg/.local/lib/python3.6/site-packages/ledgerwallet/manifest.py", line 159, in serialize_parameters
    return params.AppParams.build(parameters)
  File "/home/andrelpg/.local/lib/python3.6/site-packages/construct/core.py", line 336, in build
    self.build_stream(obj, stream, **contextkw)
  File "/home/andrelpg/.local/lib/python3.6/site-packages/construct/core.py", line 348, in build_stream
    self._build(obj, stream, context, "(building)")
  File "/home/andrelpg/.local/lib/python3.6/site-packages/construct/core.py", line 2308, in _build
    buildret = self.subcon._build(e, stream, context, path)
  File "/home/andrelpg/.local/lib/python3.6/site-packages/construct/core.py", line 2005, in _build
    buildret = sc._build(subobj, stream, context, path)
  File "/home/andrelpg/.local/lib/python3.6/site-packages/construct/core.py", line 2443, in _build
    return self.subcon._build(obj, stream, context, path)
  File "/home/andrelpg/.local/lib/python3.6/site-packages/construct/core.py", line 3634, in _build
    return sc._build(obj, stream, context, path)
  File "/home/andrelpg/.local/lib/python3.6/site-packages/construct/core.py", line 702, in _build
    buildret = self.subcon._build(obj2, stream, context, path)
  File "/home/andrelpg/.local/lib/python3.6/site-packages/construct/core.py", line 4387, in _build
    self.lengthfield._build(length, stream, context, path)
  File "/home/andrelpg/.local/lib/python3.6/site-packages/ledgerwallet/params.py", line 56, in _build
    stream_write(stream, int2byte(num), 1)
TypeError: stream_write() missing 1 required positional argument: 'path'`

My app.json manifest file:
`{
    "name": "electroneum",
    "version": "1.0.0",
    "icon": "images/icon_electroneum.gif",
    "targetId": "0x31100004",
    "flags": "0x240",
    "derivationPath": {
        "path": "2147483692/2147484063",
        "curves": ["secp256k1"]
    },
    "binary": "bin/app.hex",
    "dataSize": 640
}`

Thanks

**Comment by jibeee** [comment]
Fixed in d91a2bf506e013fc177564eb8774e9a4ed7a260e.
