### ISSUE TITLE
Constantly getting OSError: open failed with Nano X on ubuntu

### ISSUE THREAD

**Issue by phuongnd08** [LedgerHQ/ledgerctl#77]
I used to be able to use ledgerctl to access the device a few months ago, but recently for some unknown reason, things goes broken:

```
$ ledgerctl install-ca Dev
Traceback (most recent call last):
  File "/home/phuongnd08/.local/bin/ledgerctl", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/phuongnd08/.local/lib/python3.10/site-packages/ledgerwallet/ledgerctl.py", line 310, in install_ca
    get_client().install_ca(name, pubkey_bytes)
  File "/home/phuongnd08/.local/lib/python3.10/site-packages/ledgerwallet/ledgerctl.py", line 108, in get_client
    return LedgerClient(private_key=get_private_key())
  File "/home/phuongnd08/.local/lib/python3.10/site-packages/ledgerwallet/client.py", line 127, in __init__
    self.device.open()
  File "/home/phuongnd08/.local/lib/python3.10/site-packages/ledgerwallet/transport/hid.py", line 30, in open
    self.device.open_path(self.path)
  File "hid.pyx", line 157, in hid.device.open_path
OSError: open failed
```

There was suggestion to add udev rules to allow access but I tried and it still yield the same error:

```
$ wget -q -O - https://raw.githubusercontent.com/LedgerHQ/udev-rules/master/add_udev_rules.sh | sudo bash
$ ledgerctl install-ca Dev
Traceback (most recent call last):
  File "/home/phuongnd08/.local/bin/ledgerctl", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/phuongnd08/.local/lib/python3.10/site-packages/ledgerwallet/ledgerctl.py", line 310, in install_ca
    get_client().install_ca(name, pubkey_bytes)
  File "/home/phuongnd08/.local/lib/python3.10/site-packages/ledgerwallet/ledgerctl.py", line 108, in get_client
    return LedgerClient(private_key=get_private_key())
  File "/home/phuongnd08/.local/lib/python3.10/site-packages/ledgerwallet/client.py", line 127, in __init__
    self.device.open()
  File "/home/phuongnd08/.local/lib/python3.10/site-packages/ledgerwallet/transport/hid.py", line 30, in open
    self.device.open_path(self.path)
  File "hid.pyx", line 157, in hid.device.open_path
OSError: open failed
```

Is there a way to fix this?

**Comment by phuongnd08** [comment]
Device is present

```
$ lsusb
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 008: ID 2c97:4011 Ledger Nano X
```

**Comment by phuongnd08** [comment]
It's weird, but changing USB port does fix the problem.
